/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSupcalIndexRouteImport } from './routes/_authenticated/supcal/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSupcalRecordsRouteImport } from './routes/_authenticated/supcal/records'
import { Route as AuthenticatedSupcalProfileRouteImport } from './routes/_authenticated/supcal/profile'
import { Route as AuthenticatedSupcalCreateRouteImport } from './routes/_authenticated/supcal/create'
import { Route as AuthenticatedSupcalCalendar9RouteImport } from './routes/_authenticated/supcal/calendar-9'
import { Route as AuthenticatedSupcalCalendar8RouteImport } from './routes/_authenticated/supcal/calendar-8'
import { Route as AuthenticatedSupcalCalendar7RouteImport } from './routes/_authenticated/supcal/calendar-7'
import { Route as AuthenticatedSupcalCalendar6RouteImport } from './routes/_authenticated/supcal/calendar-6'
import { Route as AuthenticatedSupcalCalendar5RouteImport } from './routes/_authenticated/supcal/calendar-5'
import { Route as AuthenticatedSupcalCalendar4RouteImport } from './routes/_authenticated/supcal/calendar-4'
import { Route as AuthenticatedSupcalCalendar3RouteImport } from './routes/_authenticated/supcal/calendar-3'
import { Route as AuthenticatedSupcalCalendar2RouteImport } from './routes/_authenticated/supcal/calendar-2'
import { Route as AuthenticatedSupcalCalendar15RouteImport } from './routes/_authenticated/supcal/calendar-15'
import { Route as AuthenticatedSupcalCalendar14RouteImport } from './routes/_authenticated/supcal/calendar-14'
import { Route as AuthenticatedSupcalCalendar13RouteImport } from './routes/_authenticated/supcal/calendar-13'
import { Route as AuthenticatedSupcalCalendar12RouteImport } from './routes/_authenticated/supcal/calendar-12'
import { Route as AuthenticatedSupcalCalendar11RouteImport } from './routes/_authenticated/supcal/calendar-11'
import { Route as AuthenticatedSupcalCalendar10RouteImport } from './routes/_authenticated/supcal/calendar-10'
import { Route as AuthenticatedSupcalCalendar1RouteImport } from './routes/_authenticated/supcal/calendar-1'
import { Route as AuthenticatedSupcalCalendarRouteImport } from './routes/_authenticated/supcal/calendar'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSupcalEditIdRouteImport } from './routes/_authenticated/supcal/edit.$id'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupcalIndexRoute =
  AuthenticatedSupcalIndexRouteImport.update({
    id: '/supcal/',
    path: '/supcal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSupcalRecordsRoute =
  AuthenticatedSupcalRecordsRouteImport.update({
    id: '/supcal/records',
    path: '/supcal/records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalProfileRoute =
  AuthenticatedSupcalProfileRouteImport.update({
    id: '/supcal/profile',
    path: '/supcal/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCreateRoute =
  AuthenticatedSupcalCreateRouteImport.update({
    id: '/supcal/create',
    path: '/supcal/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar9Route =
  AuthenticatedSupcalCalendar9RouteImport.update({
    id: '/supcal/calendar-9',
    path: '/supcal/calendar-9',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar8Route =
  AuthenticatedSupcalCalendar8RouteImport.update({
    id: '/supcal/calendar-8',
    path: '/supcal/calendar-8',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar7Route =
  AuthenticatedSupcalCalendar7RouteImport.update({
    id: '/supcal/calendar-7',
    path: '/supcal/calendar-7',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar6Route =
  AuthenticatedSupcalCalendar6RouteImport.update({
    id: '/supcal/calendar-6',
    path: '/supcal/calendar-6',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar5Route =
  AuthenticatedSupcalCalendar5RouteImport.update({
    id: '/supcal/calendar-5',
    path: '/supcal/calendar-5',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar4Route =
  AuthenticatedSupcalCalendar4RouteImport.update({
    id: '/supcal/calendar-4',
    path: '/supcal/calendar-4',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar3Route =
  AuthenticatedSupcalCalendar3RouteImport.update({
    id: '/supcal/calendar-3',
    path: '/supcal/calendar-3',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar2Route =
  AuthenticatedSupcalCalendar2RouteImport.update({
    id: '/supcal/calendar-2',
    path: '/supcal/calendar-2',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar15Route =
  AuthenticatedSupcalCalendar15RouteImport.update({
    id: '/supcal/calendar-15',
    path: '/supcal/calendar-15',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar14Route =
  AuthenticatedSupcalCalendar14RouteImport.update({
    id: '/supcal/calendar-14',
    path: '/supcal/calendar-14',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar13Route =
  AuthenticatedSupcalCalendar13RouteImport.update({
    id: '/supcal/calendar-13',
    path: '/supcal/calendar-13',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar12Route =
  AuthenticatedSupcalCalendar12RouteImport.update({
    id: '/supcal/calendar-12',
    path: '/supcal/calendar-12',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar11Route =
  AuthenticatedSupcalCalendar11RouteImport.update({
    id: '/supcal/calendar-11',
    path: '/supcal/calendar-11',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar10Route =
  AuthenticatedSupcalCalendar10RouteImport.update({
    id: '/supcal/calendar-10',
    path: '/supcal/calendar-10',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendar1Route =
  AuthenticatedSupcalCalendar1RouteImport.update({
    id: '/supcal/calendar-1',
    path: '/supcal/calendar-1',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalCalendarRoute =
  AuthenticatedSupcalCalendarRouteImport.update({
    id: '/supcal/calendar',
    path: '/supcal/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupcalEditIdRoute =
  AuthenticatedSupcalEditIdRouteImport.update({
    id: '/supcal/edit/$id',
    path: '/supcal/edit/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/supcal/calendar': typeof AuthenticatedSupcalCalendarRoute
  '/supcal/calendar-1': typeof AuthenticatedSupcalCalendar1Route
  '/supcal/calendar-10': typeof AuthenticatedSupcalCalendar10Route
  '/supcal/calendar-11': typeof AuthenticatedSupcalCalendar11Route
  '/supcal/calendar-12': typeof AuthenticatedSupcalCalendar12Route
  '/supcal/calendar-13': typeof AuthenticatedSupcalCalendar13Route
  '/supcal/calendar-14': typeof AuthenticatedSupcalCalendar14Route
  '/supcal/calendar-15': typeof AuthenticatedSupcalCalendar15Route
  '/supcal/calendar-2': typeof AuthenticatedSupcalCalendar2Route
  '/supcal/calendar-3': typeof AuthenticatedSupcalCalendar3Route
  '/supcal/calendar-4': typeof AuthenticatedSupcalCalendar4Route
  '/supcal/calendar-5': typeof AuthenticatedSupcalCalendar5Route
  '/supcal/calendar-6': typeof AuthenticatedSupcalCalendar6Route
  '/supcal/calendar-7': typeof AuthenticatedSupcalCalendar7Route
  '/supcal/calendar-8': typeof AuthenticatedSupcalCalendar8Route
  '/supcal/calendar-9': typeof AuthenticatedSupcalCalendar9Route
  '/supcal/create': typeof AuthenticatedSupcalCreateRoute
  '/supcal/profile': typeof AuthenticatedSupcalProfileRoute
  '/supcal/records': typeof AuthenticatedSupcalRecordsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/supcal/': typeof AuthenticatedSupcalIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/supcal/edit/$id': typeof AuthenticatedSupcalEditIdRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/supcal/calendar': typeof AuthenticatedSupcalCalendarRoute
  '/supcal/calendar-1': typeof AuthenticatedSupcalCalendar1Route
  '/supcal/calendar-10': typeof AuthenticatedSupcalCalendar10Route
  '/supcal/calendar-11': typeof AuthenticatedSupcalCalendar11Route
  '/supcal/calendar-12': typeof AuthenticatedSupcalCalendar12Route
  '/supcal/calendar-13': typeof AuthenticatedSupcalCalendar13Route
  '/supcal/calendar-14': typeof AuthenticatedSupcalCalendar14Route
  '/supcal/calendar-15': typeof AuthenticatedSupcalCalendar15Route
  '/supcal/calendar-2': typeof AuthenticatedSupcalCalendar2Route
  '/supcal/calendar-3': typeof AuthenticatedSupcalCalendar3Route
  '/supcal/calendar-4': typeof AuthenticatedSupcalCalendar4Route
  '/supcal/calendar-5': typeof AuthenticatedSupcalCalendar5Route
  '/supcal/calendar-6': typeof AuthenticatedSupcalCalendar6Route
  '/supcal/calendar-7': typeof AuthenticatedSupcalCalendar7Route
  '/supcal/calendar-8': typeof AuthenticatedSupcalCalendar8Route
  '/supcal/calendar-9': typeof AuthenticatedSupcalCalendar9Route
  '/supcal/create': typeof AuthenticatedSupcalCreateRoute
  '/supcal/profile': typeof AuthenticatedSupcalProfileRoute
  '/supcal/records': typeof AuthenticatedSupcalRecordsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/supcal': typeof AuthenticatedSupcalIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/supcal/edit/$id': typeof AuthenticatedSupcalEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/supcal/calendar': typeof AuthenticatedSupcalCalendarRoute
  '/_authenticated/supcal/calendar-1': typeof AuthenticatedSupcalCalendar1Route
  '/_authenticated/supcal/calendar-10': typeof AuthenticatedSupcalCalendar10Route
  '/_authenticated/supcal/calendar-11': typeof AuthenticatedSupcalCalendar11Route
  '/_authenticated/supcal/calendar-12': typeof AuthenticatedSupcalCalendar12Route
  '/_authenticated/supcal/calendar-13': typeof AuthenticatedSupcalCalendar13Route
  '/_authenticated/supcal/calendar-14': typeof AuthenticatedSupcalCalendar14Route
  '/_authenticated/supcal/calendar-15': typeof AuthenticatedSupcalCalendar15Route
  '/_authenticated/supcal/calendar-2': typeof AuthenticatedSupcalCalendar2Route
  '/_authenticated/supcal/calendar-3': typeof AuthenticatedSupcalCalendar3Route
  '/_authenticated/supcal/calendar-4': typeof AuthenticatedSupcalCalendar4Route
  '/_authenticated/supcal/calendar-5': typeof AuthenticatedSupcalCalendar5Route
  '/_authenticated/supcal/calendar-6': typeof AuthenticatedSupcalCalendar6Route
  '/_authenticated/supcal/calendar-7': typeof AuthenticatedSupcalCalendar7Route
  '/_authenticated/supcal/calendar-8': typeof AuthenticatedSupcalCalendar8Route
  '/_authenticated/supcal/calendar-9': typeof AuthenticatedSupcalCalendar9Route
  '/_authenticated/supcal/create': typeof AuthenticatedSupcalCreateRoute
  '/_authenticated/supcal/profile': typeof AuthenticatedSupcalProfileRoute
  '/_authenticated/supcal/records': typeof AuthenticatedSupcalRecordsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/supcal/': typeof AuthenticatedSupcalIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/supcal/edit/$id': typeof AuthenticatedSupcalEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/supcal/calendar'
    | '/supcal/calendar-1'
    | '/supcal/calendar-10'
    | '/supcal/calendar-11'
    | '/supcal/calendar-12'
    | '/supcal/calendar-13'
    | '/supcal/calendar-14'
    | '/supcal/calendar-15'
    | '/supcal/calendar-2'
    | '/supcal/calendar-3'
    | '/supcal/calendar-4'
    | '/supcal/calendar-5'
    | '/supcal/calendar-6'
    | '/supcal/calendar-7'
    | '/supcal/calendar-8'
    | '/supcal/calendar-9'
    | '/supcal/create'
    | '/supcal/profile'
    | '/supcal/records'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/chats/'
    | '/help-center/'
    | '/settings/'
    | '/supcal/'
    | '/tasks/'
    | '/users/'
    | '/supcal/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/supcal/calendar'
    | '/supcal/calendar-1'
    | '/supcal/calendar-10'
    | '/supcal/calendar-11'
    | '/supcal/calendar-12'
    | '/supcal/calendar-13'
    | '/supcal/calendar-14'
    | '/supcal/calendar-15'
    | '/supcal/calendar-2'
    | '/supcal/calendar-3'
    | '/supcal/calendar-4'
    | '/supcal/calendar-5'
    | '/supcal/calendar-6'
    | '/supcal/calendar-7'
    | '/supcal/calendar-8'
    | '/supcal/calendar-9'
    | '/supcal/create'
    | '/supcal/profile'
    | '/supcal/records'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/supcal'
    | '/tasks'
    | '/users'
    | '/supcal/edit/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/supcal/calendar'
    | '/_authenticated/supcal/calendar-1'
    | '/_authenticated/supcal/calendar-10'
    | '/_authenticated/supcal/calendar-11'
    | '/_authenticated/supcal/calendar-12'
    | '/_authenticated/supcal/calendar-13'
    | '/_authenticated/supcal/calendar-14'
    | '/_authenticated/supcal/calendar-15'
    | '/_authenticated/supcal/calendar-2'
    | '/_authenticated/supcal/calendar-3'
    | '/_authenticated/supcal/calendar-4'
    | '/_authenticated/supcal/calendar-5'
    | '/_authenticated/supcal/calendar-6'
    | '/_authenticated/supcal/calendar-7'
    | '/_authenticated/supcal/calendar-8'
    | '/_authenticated/supcal/calendar-9'
    | '/_authenticated/supcal/create'
    | '/_authenticated/supcal/profile'
    | '/_authenticated/supcal/records'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/supcal/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/supcal/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/': {
      id: '/_authenticated/supcal/'
      path: '/supcal'
      fullPath: '/supcal/'
      preLoaderRoute: typeof AuthenticatedSupcalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/supcal/records': {
      id: '/_authenticated/supcal/records'
      path: '/supcal/records'
      fullPath: '/supcal/records'
      preLoaderRoute: typeof AuthenticatedSupcalRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/profile': {
      id: '/_authenticated/supcal/profile'
      path: '/supcal/profile'
      fullPath: '/supcal/profile'
      preLoaderRoute: typeof AuthenticatedSupcalProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/create': {
      id: '/_authenticated/supcal/create'
      path: '/supcal/create'
      fullPath: '/supcal/create'
      preLoaderRoute: typeof AuthenticatedSupcalCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-9': {
      id: '/_authenticated/supcal/calendar-9'
      path: '/supcal/calendar-9'
      fullPath: '/supcal/calendar-9'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar9RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-8': {
      id: '/_authenticated/supcal/calendar-8'
      path: '/supcal/calendar-8'
      fullPath: '/supcal/calendar-8'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar8RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-7': {
      id: '/_authenticated/supcal/calendar-7'
      path: '/supcal/calendar-7'
      fullPath: '/supcal/calendar-7'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar7RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-6': {
      id: '/_authenticated/supcal/calendar-6'
      path: '/supcal/calendar-6'
      fullPath: '/supcal/calendar-6'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar6RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-5': {
      id: '/_authenticated/supcal/calendar-5'
      path: '/supcal/calendar-5'
      fullPath: '/supcal/calendar-5'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar5RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-4': {
      id: '/_authenticated/supcal/calendar-4'
      path: '/supcal/calendar-4'
      fullPath: '/supcal/calendar-4'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar4RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-3': {
      id: '/_authenticated/supcal/calendar-3'
      path: '/supcal/calendar-3'
      fullPath: '/supcal/calendar-3'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar3RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-2': {
      id: '/_authenticated/supcal/calendar-2'
      path: '/supcal/calendar-2'
      fullPath: '/supcal/calendar-2'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar2RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-15': {
      id: '/_authenticated/supcal/calendar-15'
      path: '/supcal/calendar-15'
      fullPath: '/supcal/calendar-15'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar15RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-14': {
      id: '/_authenticated/supcal/calendar-14'
      path: '/supcal/calendar-14'
      fullPath: '/supcal/calendar-14'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar14RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-13': {
      id: '/_authenticated/supcal/calendar-13'
      path: '/supcal/calendar-13'
      fullPath: '/supcal/calendar-13'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar13RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-12': {
      id: '/_authenticated/supcal/calendar-12'
      path: '/supcal/calendar-12'
      fullPath: '/supcal/calendar-12'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar12RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-11': {
      id: '/_authenticated/supcal/calendar-11'
      path: '/supcal/calendar-11'
      fullPath: '/supcal/calendar-11'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar11RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-10': {
      id: '/_authenticated/supcal/calendar-10'
      path: '/supcal/calendar-10'
      fullPath: '/supcal/calendar-10'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar10RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar-1': {
      id: '/_authenticated/supcal/calendar-1'
      path: '/supcal/calendar-1'
      fullPath: '/supcal/calendar-1'
      preLoaderRoute: typeof AuthenticatedSupcalCalendar1RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/calendar': {
      id: '/_authenticated/supcal/calendar'
      path: '/supcal/calendar'
      fullPath: '/supcal/calendar'
      preLoaderRoute: typeof AuthenticatedSupcalCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supcal/edit/$id': {
      id: '/_authenticated/supcal/edit/$id'
      path: '/supcal/edit/$id'
      fullPath: '/supcal/edit/$id'
      preLoaderRoute: typeof AuthenticatedSupcalEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSupcalCalendarRoute: typeof AuthenticatedSupcalCalendarRoute
  AuthenticatedSupcalCalendar1Route: typeof AuthenticatedSupcalCalendar1Route
  AuthenticatedSupcalCalendar10Route: typeof AuthenticatedSupcalCalendar10Route
  AuthenticatedSupcalCalendar11Route: typeof AuthenticatedSupcalCalendar11Route
  AuthenticatedSupcalCalendar12Route: typeof AuthenticatedSupcalCalendar12Route
  AuthenticatedSupcalCalendar13Route: typeof AuthenticatedSupcalCalendar13Route
  AuthenticatedSupcalCalendar14Route: typeof AuthenticatedSupcalCalendar14Route
  AuthenticatedSupcalCalendar15Route: typeof AuthenticatedSupcalCalendar15Route
  AuthenticatedSupcalCalendar2Route: typeof AuthenticatedSupcalCalendar2Route
  AuthenticatedSupcalCalendar3Route: typeof AuthenticatedSupcalCalendar3Route
  AuthenticatedSupcalCalendar4Route: typeof AuthenticatedSupcalCalendar4Route
  AuthenticatedSupcalCalendar5Route: typeof AuthenticatedSupcalCalendar5Route
  AuthenticatedSupcalCalendar6Route: typeof AuthenticatedSupcalCalendar6Route
  AuthenticatedSupcalCalendar7Route: typeof AuthenticatedSupcalCalendar7Route
  AuthenticatedSupcalCalendar8Route: typeof AuthenticatedSupcalCalendar8Route
  AuthenticatedSupcalCalendar9Route: typeof AuthenticatedSupcalCalendar9Route
  AuthenticatedSupcalCreateRoute: typeof AuthenticatedSupcalCreateRoute
  AuthenticatedSupcalProfileRoute: typeof AuthenticatedSupcalProfileRoute
  AuthenticatedSupcalRecordsRoute: typeof AuthenticatedSupcalRecordsRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedSupcalIndexRoute: typeof AuthenticatedSupcalIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedSupcalEditIdRoute: typeof AuthenticatedSupcalEditIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSupcalCalendarRoute: AuthenticatedSupcalCalendarRoute,
  AuthenticatedSupcalCalendar1Route: AuthenticatedSupcalCalendar1Route,
  AuthenticatedSupcalCalendar10Route: AuthenticatedSupcalCalendar10Route,
  AuthenticatedSupcalCalendar11Route: AuthenticatedSupcalCalendar11Route,
  AuthenticatedSupcalCalendar12Route: AuthenticatedSupcalCalendar12Route,
  AuthenticatedSupcalCalendar13Route: AuthenticatedSupcalCalendar13Route,
  AuthenticatedSupcalCalendar14Route: AuthenticatedSupcalCalendar14Route,
  AuthenticatedSupcalCalendar15Route: AuthenticatedSupcalCalendar15Route,
  AuthenticatedSupcalCalendar2Route: AuthenticatedSupcalCalendar2Route,
  AuthenticatedSupcalCalendar3Route: AuthenticatedSupcalCalendar3Route,
  AuthenticatedSupcalCalendar4Route: AuthenticatedSupcalCalendar4Route,
  AuthenticatedSupcalCalendar5Route: AuthenticatedSupcalCalendar5Route,
  AuthenticatedSupcalCalendar6Route: AuthenticatedSupcalCalendar6Route,
  AuthenticatedSupcalCalendar7Route: AuthenticatedSupcalCalendar7Route,
  AuthenticatedSupcalCalendar8Route: AuthenticatedSupcalCalendar8Route,
  AuthenticatedSupcalCalendar9Route: AuthenticatedSupcalCalendar9Route,
  AuthenticatedSupcalCreateRoute: AuthenticatedSupcalCreateRoute,
  AuthenticatedSupcalProfileRoute: AuthenticatedSupcalProfileRoute,
  AuthenticatedSupcalRecordsRoute: AuthenticatedSupcalRecordsRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedSupcalIndexRoute: AuthenticatedSupcalIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedSupcalEditIdRoute: AuthenticatedSupcalEditIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
